# Generated by Django 3.2.10 on 2021-12-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynotification',
            name='last_sent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
