version: "3.9"
   
services:
  db:
    image: postgres:12
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  
  api:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:${PORT}"
    volumes:
      - ./app:/code
    ports:
      - "${PORT}:${PORT}"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_SETTINGS_MODULE=mintally.settings
    depends_on:
      - db
    restart: on-failure
  
  rabbitmq:
      image: rabbitmq:management-alpine
      hostname: rabbitmq
      restart: on-failure

  celeryworker:
    build: .
    command: celery -A mintally worker -l info
    volumes:
      - ./app:/code
    environment:
      - CELERY_BROKER=amqp://guest:guest@rabbitmq:5672
    restart: on-failure
    depends_on:
      - rabbitmq

  celerybeat:
    build: .
    command: celery -A mintally beat -l info
    volumes:
      - ./app:/code
    environment:
      - CELERY_BROKER=amqp://guest:guest@rabbitmq:5672
    restart: on-failure

