# Generated by Django 3.2.10 on 2021-12-10 22:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mood', models.CharField(choices=[('positive', 'positive'), ('neutral', 'neutral'), ('negative', 'negative')], default='neutral', max_length=32)),
                ('note', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_statuses', to='core.profile')),
            ],
        ),
    ]
