# Generated by Django 3.2.10 on 2021-12-11 16:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('error', 'error')], default='pending', max_length=32)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=500)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='contacts.helpcontact')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='contacts.shipment')),
            ],
        ),
    ]
