# Generated by Django 3.2.10 on 2021-12-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_shipment_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='sent_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sms',
            name='sent_at',
            field=models.DateTimeField(),
        ),
    ]
